name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the dev environment Docker image
      run: |
        docker build . --tag ghcr.io/magister_zito/docker-dev-env:latest
        docker run ghcr.io/magister_zito/docker-dev-env:latest
        docker push ghcr.io/magister_zito/docker-dev-env:latest
